### ISSUE TITLE
Android Studio Kurulumu

### ISSUE THREAD

**Issue by kerimkaraca** [kerimkaraca/android-courses#3]
Android Studio (yoksa JDK 8) kurulacak. Empty proje oluşturulacak, telefon bağlanıp çalıştığı teyit edilecek.

**Comment by kubranilgun** [comment]
Android Studio Version 2.2.1 kuruldu.

**Comment by kubranilgun** [comment]
Yeni bilgisayara Android Studio Version 3.2.1 kuruldu.

**Comment by kubranilgun** [comment]
Android Studio Version 3.3.1 kuruldu.
